USE DEMO;
CREATE TABLE ORDERR (
    ORDERID INT,
    CUSTOMERID INT,
    EMPLOYEEID INT,
    ORDERDATAE DATE,
    SHIPPERID INT
);
INSERT INTO ORDERR
            VALUES
            (10308, 2, 7, '1996-09-18', 3),
			(10309, 37, 3, '1996-09-19', 1),
			(10310, 77, 8, '1996-09-20', 2);

SELECT 
    *
FROM
    ORDERR;
CREATE TABLE CUSTOMERS (
    CUSTOMERID INT,
    CUSTOMERNAME VARCHAR(20),
    CONTACTNAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    CITY VARCHAR(20),
    POSTALCODE INT,
    COUNTRY VARCHAR(20)
);
INSERT INTO CUSTOMERS
			VALUES
			(1, 'ALFRED FUTTERKISTE', 'MARIA ANDRES', 'OBERE STR. 57', 'BERLIN', 12209, 'GERMANY'),
			(2, 'ANA TRUJILLO HELADOS', 'ANA TRUJILLO', 'AVDA. DE LA CONSTITUCION ', 'MEXICO D.F', 05021, 'MEXICO'),
            (3, 'ANTONIO MORENO TAQUERIA', 'ANTONIO MORENO', 'MATADEROS 2312', 'MEXICO D.F', 05023, 'MEXICO');
SELECT * FROM CUSTOMERS;
SELECT 
    ORDERR.ORDERID, CUSTOMERS.CUSTOMERNAME
FROM
    ORDERR
        INNER JOIN
    CUSTOMERS ON ORDERR.CUSTOMERID = CUSTOMERS.CUSTOMERID;
SELECT 
    ORDERR.ORDERID, CUSTOMERS.CUSTOMERID, ORDERR.SHIPPERID
FROM
    ORDERR
        INNER JOIN
    CUSTOMERS ON ORDERR.CUSTOMERID = CUSTOMERS.CUSTOMERID;
    
SELECT 
    ORDERR.ORDERID, CUSTOMERS.CUSTOMERID
FROM
    CUSTOMERS
        LEFT JOIN
    ORDERR ON ORDERR.CUSTOMERID = CUSTOMERS.CUSTOMERID
ORDER BY CUSTOMERS.CUSTOMERNAME;

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT,
    LASTNAME VARCHAR(20),
    FIRSTNAME VARCHAR(20),
    BIRTHDATE DATE,
    PHOTO VARCHAR(20)
);
INSERT INTO EMPLOYEES
            VALUES
            (1, 'DAVOLIO', 'NANCY', '1968-12-08', 'EMPID1.PIC'),
            (2, 'FULLER', 'ANDREW', '1952-02-19', 'EMPID2.PIC'),
            (3, 'LEVERLING', 'JANET', '1963-08-30', 'EMPID3.PIC');
SELECT * FROM EMPLOYEES;
CREATE TABLE TEST (
    ORDERID INT,
    CUSTOMERID INT,
    EMPLOYEEID INT,
    ORDERDATAE DATE,
    SHIPPERID INT
);
INSERT INTO TEST
            VALUES
            (10308, 2, 7, '1996-09-18', 3),
			(10309, 37, 3, '1996-09-19', 1),
			(10310, 77, 8, '1996-09-20', 2);
SELECT * FROM TEST;
SELECT 
    TEST.ORDERID, EMPLOYEES.LASTNAME, EMPLOYEES.FIRSTNAME
FROM
    TEST
        RIGHT JOIN
    EMPLOYEES ON TEST.EMPLOYEEID = EMPLOYEES.EMPLOYEEID
ORDER BY TEST.ORDERID;